### ISSUE TITLE
undefined method name for #<OpenSSL::X509::Name:0x007f420033d8c8>

### ISSUE THREAD

**Issue by laoshancun** [r509/r509-ocsp-responder#17]
hi,i got this error when  follow tutorial guide.
```
/ # rackup -p 8080
W, [2017-04-24T02:47:22.380489 #77]  WARN -- : Loading redis with standard ruby driver
Enter PEM pass phrase:
/usr/local/bundle/gems/r509-ocsp-responder-0.3.3/lib/r509/ocsp/signer.rb:75:in `block in initialize': undefined method `name' for #<OpenSSL::X509::Name:0x007f420033d8c8> (NoMethodError)
        from /usr/local/bundle/gems/r509-ocsp-responder-0.3.3/lib/r509/ocsp/signer.rb:73:in `each'
        from /usr/local/bundle/gems/r509-ocsp-responder-0.3.3/lib/r509/ocsp/signer.rb:73:in `initialize'
        from /usr/local/bundle/gems/r509-ocsp-responder-0.3.3/lib/r509/ocsp/signer.rb:21:in `new'
        from /usr/local/bundle/gems/r509-ocsp-responder-0.3.3/lib/r509/ocsp/signer.rb:21:in `initialize'
        from /usr/local/bundle/gems/r509-ocsp-responder-0.3.3/lib/r509/ocsp/responder/ocsp-config.rb:14:in `new'
        from /usr/local/bundle/gems/r509-ocsp-responder-0.3.3/lib/r509/ocsp/responder/ocsp-config.rb:14:in `load_config'
        from /config.ru:20:in `block in <main>'
        from /usr/local/bundle/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/local/bundle/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
        from /config.ru:in `new'
        from /config.ru:in `<main>'
        from /usr/local/bundle/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
        from /usr/local/bundle/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
        from /usr/local/bundle/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
        from /usr/local/bundle/gems/rack-1.6.5/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from /usr/local/bundle/gems/rack-1.6.5/lib/rack/server.rb:208:in `app'
        from /usr/local/bundle/gems/rack-1.6.5/lib/rack/server.rb:336:in `wrapped_app'
        from /usr/local/bundle/gems/rack-1.6.5/lib/rack/server.rb:272:in `start'
        from /usr/local/bundle/gems/rack-1.6.5/lib/rack/server.rb:147:in `start'
        from /usr/local/bundle/gems/rack-1.6.5/bin/rackup:4:in `<top (required)>'
        from /usr/local/bundle/bin/rackup:22:in `load'
        from /usr/local/bundle/bin/rackup:22:in `<main>'
```

**Comment by reaperhulk** [comment]
Are you running on the latest Ruby? I've seen some reports that the latest Ruby significantly changes the OpenSSL APIs (https://github.com/r509/r509/issues/122). Unfortunately no one has stepped forward to resolve this and I don't work in Ruby much these days.

**Comment by laoshancun** [comment]
yeah, i am using ruby 2.4.1p111 .what is the latest version r509 support?

**Comment by reaperhulk** [comment]
Probably 2.3, but you'd have to test.

**Comment by laoshancun** [comment]
ok,thanks!
